version: "3.9"

services:
  database:
    container_name: live-feed-database
    image: postgres:16
    restart: unless-stopped
    env_file:
      - ./server/.env.local
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data