[package]
name = "backend"
version = "0.1.0"
edition = "2021"

[dependencies]
http = "1.3.1"
reqwest = { version = "0.12.15", default-features = false, features = ["brotli", "deflate", "gzip", "json", "rustls-tls"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
tokio = { version = "1.44.1", features = ["full"] }
